name: Build and Deploy

env:
  GLOBAL_CONNECTED_APP_STRING: ${{ secrets.CONNECTED_APP_STRING }}
  GLOBAL_CONNECTED_APP_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
  GLOBAL_CONNECTED_APP_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
  GLOBAL_PAT: ${{ secrets.PAT }}
  GLOBAL_TARGET: ${{ vars.TARGET }}
  GLOBAL_ENVIRONMENT: Development

on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
        type: string
      branch:
        required: true
        default: develop
        type: string
      vCore:
        required: true
        type: choice
        options: ["0.1","0.2","0.5","1"]
      replicas:
        required: true
        type: choice
        options: ["1","2"]

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ inputs.repository }}
          ref: ${{ inputs.branch }}
          token: ${{ env.GLOBAL_PAT }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.12.0
        with:
          java-version: 17
          maven-version: 3.9.9

      - name: Build
        run: |
          mvn clean package -DskipTests

      - name: Deploy
        run: |
          mvn deploy -DmuleDeploy \
          -Dmule.env=${{ env.GLOBAL_ENVIRONMENT }} \
          -Danypoint.platform.client_id=${{ env.GLOBAL_CONNECTED_APP_CLIENT_ID }} \
          -Danypoint.platform.client_secret=${{ env.GLOBAL_CONNECTED_APP_CLIENT_SECRET }}
