name: Build and Deploy

env:
  GLOBAL_CONNECTED_APP_CLIENT_ID: ${{ secrets.CONNECTED_APP_CLIENT_ID }}
  GLOBAL_CONNECTED_APP_CLIENT_SECRET: ${{ secrets.CONNECTED_APP_CLIENT_SECRET }}
  GLOBAL_PAT: ${{ secrets.PAT }}

on:
  workflow_dispatch:
    inputs:
      repository:
        required: true
        type: string
      branch:
        required: true
        default: develop
        type: string
      environment:
        required: true
        type: choice
        options: [DEV]

jobs:
  Build-Deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/${{ inputs.repository }}
          ref: ${{ inputs.branch }}
          token: ${{ env.GLOBAL_PAT }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.12.0
        with:
          java-version: 17
          maven-version: 3.9.9

      - name: Build
        run: mvn clean package -DskipTests

      - name: Deploy
        run: |
          mvn deploy -DmuleDeploy -DskipTests \
          -Dmule.env=Development \
          -DconnectedAppClientId=${{ env.GLOBAL_CONNECTED_APP_CLIENT_ID }} \
          -DconnectedAppClientSecret=${{ env.GLOBAL_CONNECTED_APP_CLIENT_SECRET }}
